services:
  # Main application service
  app:
    image: shreeve1/ai-idea-generator:latest
    container_name: ai-idea-generator-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Database configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
      # AI service configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Email service configuration (optional)
      #- SMTP_HOST=${SMTP_HOST}
      #- SMTP_PORT=${SMTP_PORT}
      #- SMTP_USER=${SMTP_USER}
      #- SMTP_PASS=${SMTP_PASS}
      #- FROM_EMAIL=${FROM_EMAIL}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  client_node_modules:
